### ISSUE TITLE
remove hostname override in netdata.conf for API nodes

### ISSUE THREAD

**Issue by paraglade** [ThisLife/tf_netdata_thislife-dev#15]

**Comment by paraglade** [comment]
https://github.com/ThisLife/photos-packer/blob/master/config/netdata/netdata.conf#L20

**Comment by luthermonson** [comment]
https://github.com/ThisLife/photos-packer/commit/f90e274b612c30b5ea6d2652bd00eb9884ae83b6#diff-22098e7686a81490f237cd9d0ce36f50L17
